/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Alerts_list_alerts } from "../../funcs/Alerts_list_alerts.js";
import { ListAlertsRequest$zodSchema } from "../../models/listalertsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAlertsRequest$zodSchema.optional(),
};

export const tool$Alerts_list_alerts: ToolDefinition<typeof args> = {
  name: "alerts-list-alerts",
  description: `List alerts

Retrieve all alerts from third parties`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await Alerts_list_alerts(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
