/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsListIncidents } from "../../funcs/incidentsListIncidents.js";
import { ListIncidentsRequest$zodSchema } from "../../models/listincidentsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListIncidentsRequest$zodSchema.optional(),
};

export const tool$incidentsListIncidents: ToolDefinition<typeof args> = {
  name: "list-incidents",
  description: `List incidents

List all of the incidents in the organization`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await incidentsListIncidents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
