/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Incidents_create_incident } from "../../funcs/Incidents_create_incident.js";
import { CreateIncident$zodSchema } from "../../models/createincident.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateIncident$zodSchema,
};

export const tool$Incidents_create_incident: ToolDefinition<typeof args> = {
  name: "incidents-create-incident",
  description: `Create an incident

Create a new incident`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await Incidents_create_incident(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
