/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Incidents_list_incidents } from "../../funcs/Incidents_list_incidents.js";
import { ListIncidentsRequest$zodSchema } from "../../models/listincidentsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListIncidentsRequest$zodSchema.optional(),
};

export const tool$Incidents_list_incidents: ToolDefinition<typeof args> = {
  name: "incidents-list-incidents",
  description: `List incidents

List all of the incidents in the organization`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await Incidents_list_incidents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
