/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Retrospectives_list_incident_retrospectives } from "../../funcs/Retrospectives_list_incident_retrospectives.js";
import { ListIncidentRetrospectivesRequest$zodSchema } from "../../models/listincidentretrospectivesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListIncidentRetrospectivesRequest$zodSchema,
};

export const tool$Retrospectives_list_incident_retrospectives: ToolDefinition<
  typeof args
> = {
  name: "retrospectives-list-incident-retrospectives",
  description:
    `Lists all retrospectives (RCAs) for an incident. Among other things, this is useful for:

  - Getting a list of retrospectives for an incident,
  - Getting basic data about a retrospective.
  - Getting the fields of a retrospective.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await Retrospectives_list_incident_retrospectives(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
