/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { FireHydrantCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  UpdateIncidentRetrospectiveFieldRequest,
  UpdateIncidentRetrospectiveFieldRequest$zodSchema,
  UpdateIncidentRetrospectiveFieldResponse,
  UpdateIncidentRetrospectiveFieldResponse$zodSchema,
} from "../models/updateincidentretrospectivefieldop.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Update the value on a retrospective field
 *
 * @remarks
 * Update retrospective field value
 */
export function retrospectivesUpdateIncidentRetrospectiveField(
  client$: FireHydrantCore,
  request: UpdateIncidentRetrospectiveFieldRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    UpdateIncidentRetrospectiveFieldResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: FireHydrantCore,
  request: UpdateIncidentRetrospectiveFieldRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      UpdateIncidentRetrospectiveFieldResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => UpdateIncidentRetrospectiveFieldRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = encodeJSON(
    "body",
    payload$.update_incident_retrospective_field,
    { explode: true },
  );

  const pathParams$ = {
    field_id: encodeSimple("field_id", payload$.field_id, {
      explode: false,
      charEncoding: "percent",
    }),
    incident_id: encodeSimple("incident_id", payload$.incident_id, {
      explode: false,
      charEncoding: "percent",
    }),
    retrospective_id: encodeSimple(
      "retrospective_id",
      payload$.retrospective_id,
      { explode: false, charEncoding: "percent" },
    ),
  };
  const path$ = pathToFunc(
    "/v1/incidents/{incident_id}/retrospectives/{retrospective_id}/fields/{field_id}",
  )(
    pathParams$,
  );

  const headers$ = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "update_incident_retrospective_field",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "PATCH",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    body: body$,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    UpdateIncidentRetrospectiveFieldResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, UpdateIncidentRetrospectiveFieldResponse$zodSchema, {
      key: "Incidents_RetrospectiveFieldEntity",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
