/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { FireHydrantCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { Register } from "./extensions.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { registerMCPExtensions } from "./server.extensions.js";
import { createRegisterTool } from "./tools.js";
import { tool$Alerts_list_alerts } from "./tools/Alerts_list_alerts.js";
import { tool$Incidents_create_incident } from "./tools/Incidents_create_incident.js";
import { tool$Incidents_list_incidents } from "./tools/Incidents_list_incidents.js";
import { tool$Retrospectives_list_incident_retrospectives } from "./tools/Retrospectives_list_incident_retrospectives.js";
import { tool$Retrospectives_update_incident_retrospective_field } from "./tools/Retrospectives_update_incident_retrospective_field.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "FireHydrant",
    version: "0.0.1-beta.1",
  });

  const client = new FireHydrantCore({
    security: deps.security,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$Incidents_list_incidents);
  tool(tool$Incidents_create_incident);
  tool(tool$Retrospectives_list_incident_retrospectives);
  tool(tool$Retrospectives_update_incident_retrospective_field);
  tool(tool$Alerts_list_alerts);

  registerMCPExtensions(register satisfies Register);

  return server;
}
