/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AlertsSirenAlertEntity,
  AlertsSirenAlertEntity$zodSchema,
} from "./alertssirenalertentity.js";
import {
  AlertsSirenEventEntity,
  AlertsSirenEventEntity$zodSchema,
} from "./alertssirenevententity.js";
import {
  ConversationsAPIEntitiesReference,
  ConversationsAPIEntitiesReference$zodSchema,
} from "./conversationsapientitiesreference.js";
import {
  NullableSignalsAPIRuleEntity,
  NullableSignalsAPIRuleEntity$zodSchema,
} from "./nullablesignalsapiruleentity.js";
import {
  NullableSignalsAPITargetEntity,
  NullableSignalsAPITargetEntity$zodSchema,
} from "./nullablesignalsapitargetentity.js";
import {
  PublicApiv1IncidentsSuccinctEntity,
  PublicApiv1IncidentsSuccinctEntity$zodSchema,
} from "./publicapiv1incidentssuccinctentity.js";
import { SuccinctEntity, SuccinctEntity$zodSchema } from "./succinctentity.js";

/**
 * Arbitrary key:value pairs of labels.
 */
export type AlertsAlertEntityLabels = {};

export const AlertsAlertEntityLabels$zodSchema: z.ZodType<
  AlertsAlertEntityLabels,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe("Arbitrary key:value pairs of labels.");

/**
 * Alerts_AlertEntity model
 */
export type AlertsAlertEntity = {
  id?: string | null | undefined;
  summary?: string | null | undefined;
  description?: string | null | undefined;
  priority?: string | null | undefined;
  integration_name?: string | null | undefined;
  starts_at?: string | null | undefined;
  ends_at?: string | null | undefined;
  duration_ms?: number | null | undefined;
  duration_iso8601?: string | null | undefined;
  status?: string | null | undefined;
  remote_id?: string | null | undefined;
  remote_url?: string | null | undefined;
  labels?: AlertsAlertEntityLabels | null | undefined;
  environments?: Array<SuccinctEntity> | null | undefined;
  services?: Array<SuccinctEntity> | null | undefined;
  tags?: Array<string> | null | undefined;
  source_icon?: string | null | undefined;
  signal_id?: string | null | undefined;
  signal_rule?: NullableSignalsAPIRuleEntity | null | undefined;
  signal_target?: NullableSignalsAPITargetEntity | null | undefined;
  team_name?: string | null | undefined;
  team_id?: string | null | undefined;
  position?: number | null | undefined;
  incidents?: Array<PublicApiv1IncidentsSuccinctEntity> | null | undefined;
  events?: Array<AlertsSirenEventEntity> | null | undefined;
  is_expired?: boolean | null | undefined;
  is_noise?: boolean | null | undefined;
  parent_alerts?: Array<AlertsSirenAlertEntity> | null | undefined;
  child_alerts?: Array<AlertsSirenAlertEntity> | null | undefined;
  conversations?: Array<ConversationsAPIEntitiesReference> | null | undefined;
};

export const AlertsAlertEntity$zodSchema: z.ZodType<
  AlertsAlertEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  child_alerts: z.array(AlertsSirenAlertEntity$zodSchema).nullable().optional(),
  conversations: z.array(ConversationsAPIEntitiesReference$zodSchema).nullable()
    .optional(),
  description: z.string().nullable().optional(),
  duration_iso8601: z.string().nullable().optional(),
  duration_ms: z.number().int().nullable().optional(),
  ends_at: z.string().datetime({ offset: true }).nullable().optional(),
  environments: z.array(SuccinctEntity$zodSchema).nullable().optional(),
  events: z.array(AlertsSirenEventEntity$zodSchema).nullable().optional(),
  id: z.string().nullable().optional(),
  incidents: z.array(PublicApiv1IncidentsSuccinctEntity$zodSchema).nullable()
    .optional(),
  integration_name: z.string().nullable().optional(),
  is_expired: z.boolean().nullable().optional(),
  is_noise: z.boolean().nullable().optional(),
  labels: z.lazy(() => AlertsAlertEntityLabels$zodSchema).nullable().optional(),
  parent_alerts: z.array(AlertsSirenAlertEntity$zodSchema).nullable()
    .optional(),
  position: z.number().int().nullable().optional(),
  priority: z.string().nullable().optional(),
  remote_id: z.string().nullable().optional(),
  remote_url: z.string().nullable().optional(),
  services: z.array(SuccinctEntity$zodSchema).nullable().optional(),
  signal_id: z.string().nullable().optional(),
  signal_rule: NullableSignalsAPIRuleEntity$zodSchema.nullable().optional(),
  signal_target: NullableSignalsAPITargetEntity$zodSchema.nullable().optional(),
  source_icon: z.string().nullable().optional(),
  starts_at: z.string().datetime({ offset: true }).nullable().optional(),
  status: z.string().nullable().optional(),
  summary: z.string().nullable().optional(),
  tags: z.array(z.string()).nullable().optional(),
  team_id: z.string().nullable().optional(),
  team_name: z.string().nullable().optional(),
}).describe("Alerts_AlertEntity model");
