/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The event's payload
 */
export type Data = {};

export const Data$zodSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z.object(
  {},
).describe("The event's payload");

export type AlertsSirenEventEntity = {
  id?: string | null | undefined;
  type?: string | null | undefined;
  data?: Data | null | undefined;
  created_at?: string | null | undefined;
};

export const AlertsSirenEventEntity$zodSchema: z.ZodType<
  AlertsSirenEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).nullable().optional(),
  data: z.lazy(() => Data$zodSchema).nullable().optional(),
  id: z.string().nullable().optional(),
  type: z.string().nullable().optional(),
});
