/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AlertsAlertEntity,
  AlertsAlertEntity$zodSchema,
} from "./alertsalertentity.js";
import {
  NullablePaginationEntity,
  NullablePaginationEntity$zodSchema,
} from "./nullablepaginationentity.js";

/**
 * Alerts_AlertEntityPaginated model
 */
export type AlertsAlertEntityPaginated = {
  data?: Array<AlertsAlertEntity> | null | undefined;
  pagination?: NullablePaginationEntity | null | undefined;
};

export const AlertsAlertEntityPaginated$zodSchema: z.ZodType<
  AlertsAlertEntityPaginated,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(AlertsAlertEntity$zodSchema).nullable().optional(),
  pagination: NullablePaginationEntity$zodSchema.nullable().optional(),
}).describe("Alerts_AlertEntityPaginated model");
