/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NullableSignalsAPIRuleEntity,
  NullableSignalsAPIRuleEntity$zodSchema,
} from "./nullablesignalsapiruleentity.js";

/**
 * Arbitrary key:value pairs of labels.
 */
export type AlertsSirenAlertEntityLabels = {};

export const AlertsSirenAlertEntityLabels$zodSchema: z.ZodType<
  AlertsSirenAlertEntityLabels,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe("Arbitrary key:value pairs of labels.");

export type AlertsSirenAlertEntity = {
  id?: string | null | undefined;
  summary?: string | null | undefined;
  description?: string | null | undefined;
  starts_at?: string | null | undefined;
  ends_at?: string | null | undefined;
  status?: string | null | undefined;
  remote_id?: string | null | undefined;
  remote_url?: string | null | undefined;
  labels?: AlertsSirenAlertEntityLabels | null | undefined;
  tags?: Array<string> | null | undefined;
  signal_id?: string | null | undefined;
  signal_rule?: NullableSignalsAPIRuleEntity | null | undefined;
};

export const AlertsSirenAlertEntity$zodSchema: z.ZodType<
  AlertsSirenAlertEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().nullable().optional(),
  ends_at: z.string().datetime({ offset: true }).nullable().optional(),
  id: z.string().nullable().optional(),
  labels: z.lazy(() => AlertsSirenAlertEntityLabels$zodSchema).nullable()
    .optional(),
  remote_id: z.string().nullable().optional(),
  remote_url: z.string().nullable().optional(),
  signal_id: z.string().nullable().optional(),
  signal_rule: NullableSignalsAPIRuleEntity$zodSchema.nullable().optional(),
  starts_at: z.string().datetime({ offset: true }).nullable().optional(),
  status: z.string().nullable().optional(),
  summary: z.string().nullable().optional(),
  tags: z.array(z.string()).nullable().optional(),
});
