/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NullableConversationsAPIEntitiesChannel,
  NullableConversationsAPIEntitiesChannel$zodSchema,
} from "./nullableconversationsapientitieschannel.js";

export type ConversationsAPIEntitiesReference = {
  id?: string | null | undefined;
  resource_class?: string | null | undefined;
  resource_id?: string | null | undefined;
  field?: string | null | undefined;
  comments_url?: string | null | undefined;
  channel?: NullableConversationsAPIEntitiesChannel | null | undefined;
};

export const ConversationsAPIEntitiesReference$zodSchema: z.ZodType<
  ConversationsAPIEntitiesReference,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel: NullableConversationsAPIEntitiesChannel$zodSchema.nullable()
    .optional(),
  comments_url: z.string().nullable().optional(),
  field: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  resource_class: z.string().nullable().optional(),
  resource_id: z.string().nullable().optional(),
});
