/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { IncidentEntity, IncidentEntity$zodSchema } from "./incidententity.js";

export type CreateIncidentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  IncidentEntity?: IncidentEntity | undefined;
};

export const CreateIncidentResponse$zodSchema: z.ZodType<
  CreateIncidentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  IncidentEntity: IncidentEntity$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
