/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CustomFieldsFieldValue = {
  name?: string | null | undefined;
  value_type?: string | null | undefined;
  display_name?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  field_id?: string | null | undefined;
  value_array?: Array<string> | null | undefined;
  value_string?: string | null | undefined;
  value?: string | null | undefined;
};

export const CustomFieldsFieldValue$zodSchema: z.ZodType<
  CustomFieldsFieldValue,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().nullable().optional(),
  display_name: z.string().nullable().optional(),
  field_id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  slug: z.string().nullable().optional(),
  value: z.string().nullable().optional(),
  value_array: z.array(z.string()).nullable().optional(),
  value_string: z.string().nullable().optional(),
  value_type: z.string().nullable().optional(),
});
