/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  IncidentsRetrospectiveEntity,
  IncidentsRetrospectiveEntity$zodSchema,
} from "./incidentsretrospectiveentity.js";
import {
  NullablePaginationEntity,
  NullablePaginationEntity$zodSchema,
} from "./nullablepaginationentity.js";

/**
 * Incidents_RetrospectiveEntityPaginated model
 */
export type IncidentsRetrospectiveEntityPaginated = {
  data?: Array<IncidentsRetrospectiveEntity> | null | undefined;
  pagination?: NullablePaginationEntity | null | undefined;
};

export const IncidentsRetrospectiveEntityPaginated$zodSchema: z.ZodType<
  IncidentsRetrospectiveEntityPaginated,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(IncidentsRetrospectiveEntity$zodSchema).nullable().optional(),
  pagination: NullablePaginationEntity$zodSchema.nullable().optional(),
}).describe("Incidents_RetrospectiveEntityPaginated model");
