/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IncidentEntityFieldRequirementEntity = {
  field_id?: string | null | undefined;
  required_at_milestone_id?: string | null | undefined;
};

export const IncidentEntityFieldRequirementEntity$zodSchema: z.ZodType<
  IncidentEntityFieldRequirementEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  field_id: z.string().nullable().optional(),
  required_at_milestone_id: z.string().nullable().optional(),
});
