/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NullableTeamEntityLite,
  NullableTeamEntityLite$zodSchema,
} from "./nullableteamentitylite.js";

export type IncidentsTeamAssignmentEntityLite = {
  id?: string | null | undefined;
  status?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  team?: NullableTeamEntityLite | null | undefined;
};

export const IncidentsTeamAssignmentEntityLite$zodSchema: z.ZodType<
  IncidentsTeamAssignmentEntityLite,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).nullable().optional(),
  id: z.string().nullable().optional(),
  status: z.string().nullable().optional(),
  team: NullableTeamEntityLite$zodSchema.nullable().optional(),
  updated_at: z.string().datetime({ offset: true }).nullable().optional(),
});
