/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  IncidentsRetrospectiveEntitySectionEntity,
  IncidentsRetrospectiveEntitySectionEntity$zodSchema,
} from "./incidentsretrospectiveentitysectionentity.js";
import {
  IncidentsRetrospectiveFieldEntity,
  IncidentsRetrospectiveFieldEntity$zodSchema,
} from "./incidentsretrospectivefieldentity.js";

/**
 * Incidents_RetrospectiveEntity model
 */
export type IncidentsRetrospectiveEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  sections?:
    | Array<IncidentsRetrospectiveEntitySectionEntity>
    | null
    | undefined;
  is_hidden?: boolean | null | undefined;
  fields?: Array<IncidentsRetrospectiveFieldEntity> | null | undefined;
  exports?: Array<string> | null | undefined;
};

export const IncidentsRetrospectiveEntity$zodSchema: z.ZodType<
  IncidentsRetrospectiveEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().nullable().optional(),
  exports: z.array(z.string()).nullable().optional(),
  fields: z.array(IncidentsRetrospectiveFieldEntity$zodSchema).nullable()
    .optional(),
  id: z.string().nullable().optional(),
  is_hidden: z.boolean().nullable().optional(),
  name: z.string().nullable().optional(),
  sections: z.array(IncidentsRetrospectiveEntitySectionEntity$zodSchema)
    .nullable().optional(),
}).describe("Incidents_RetrospectiveEntity model");
