/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NullableAuthorEntity,
  NullableAuthorEntity$zodSchema,
} from "./nullableauthorentity.js";

export type IncidentsLifecycleMilestoneEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  position?: number | null | undefined;
  occurred_at?: string | null | undefined;
  duration?: string | null | undefined;
  updated_by?: NullableAuthorEntity | null | undefined;
  updated_at?: string | null | undefined;
};

export const IncidentsLifecycleMilestoneEntity$zodSchema: z.ZodType<
  IncidentsLifecycleMilestoneEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().nullable().optional(),
  duration: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  occurred_at: z.string().datetime({ offset: true }).nullable().optional(),
  position: z.number().int().nullable().optional(),
  slug: z.string().nullable().optional(),
  updated_at: z.string().datetime({ offset: true }).nullable().optional(),
  updated_by: NullableAuthorEntity$zodSchema.nullable().optional(),
});
