/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Incidents_ChannelEntity model
 */
export type IncidentsChannelEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  source?: string | null | undefined;
  source_name?: string | null | undefined;
  source_id?: string | null | undefined;
  url?: string | null | undefined;
  icon_url?: string | null | undefined;
  status?: string | null | undefined;
};

export const IncidentsChannelEntity$zodSchema: z.ZodType<
  IncidentsChannelEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  icon_url: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  source: z.string().nullable().optional(),
  source_id: z.string().nullable().optional(),
  source_name: z.string().nullable().optional(),
  status: z.string().nullable().optional(),
  url: z.string().nullable().optional(),
}).describe("Incidents_ChannelEntity model");
