/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NullableIntegrationEntity,
  NullableIntegrationEntity$zodSchema,
} from "./nullableintegrationentity.js";

/**
 * Incidents_StatusPageEntity model
 */
export type IncidentsStatusPageEntity = {
  id?: string | null | undefined;
  url?: string | null | undefined;
  external_id?: string | null | undefined;
  name?: string | null | undefined;
  display_name?: string | null | undefined;
  integration?: NullableIntegrationEntity | null | undefined;
};

export const IncidentsStatusPageEntity$zodSchema: z.ZodType<
  IncidentsStatusPageEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string().nullable().optional(),
  external_id: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  integration: NullableIntegrationEntity$zodSchema.nullable().optional(),
  name: z.string().nullable().optional(),
  url: z.string().nullable().optional(),
}).describe("Incidents_StatusPageEntity model");
