/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IncidentsLifecycleMeasurementEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  starts_at_milestone?: string | null | undefined;
  ends_at_milestone?: string | null | undefined;
  value?: string | null | undefined;
  calculated_at?: string | null | undefined;
};

export const IncidentsLifecycleMeasurementEntity$zodSchema: z.ZodType<
  IncidentsLifecycleMeasurementEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  calculated_at: z.string().datetime({ offset: true }).nullable().optional(),
  description: z.string().nullable().optional(),
  ends_at_milestone: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  slug: z.string().nullable().optional(),
  starts_at_milestone: z.string().nullable().optional(),
  value: z.string().nullable().optional(),
});
