/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { IncidentEntity, IncidentEntity$zodSchema } from "./incidententity.js";
import {
  NullablePaginationEntity,
  NullablePaginationEntity$zodSchema,
} from "./nullablepaginationentity.js";

/**
 * IncidentEntityPaginated model
 */
export type IncidentEntityPaginated = {
  data?: Array<IncidentEntity> | null | undefined;
  pagination?: NullablePaginationEntity | null | undefined;
};

export const IncidentEntityPaginated$zodSchema: z.ZodType<
  IncidentEntityPaginated,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(IncidentEntity$zodSchema).nullable().optional(),
  pagination: NullablePaginationEntity$zodSchema.nullable().optional(),
}).describe("IncidentEntityPaginated model");
