/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IncidentsMilestoneEntity = {
  id?: string | null | undefined;
  type?: string | null | undefined;
  duration?: string | null | undefined;
  occurred_at?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
};

export const IncidentsMilestoneEntity$zodSchema: z.ZodType<
  IncidentsMilestoneEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).nullable().optional(),
  duration: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  occurred_at: z.string().datetime({ offset: true }).nullable().optional(),
  type: z.string().nullable().optional(),
  updated_at: z.string().datetime({ offset: true }).nullable().optional(),
});
