/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NullableAuthorEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  source?: string | null | undefined;
  email?: string | null | undefined;
};

export const NullableAuthorEntity$zodSchema: z.ZodType<
  NullableAuthorEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  source: z.string().nullable().optional(),
});
