/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * SeverityMatrix_ImpactEntity model
 */
export type NullableSeverityMatrixImpactEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  type?: string | null | undefined;
  affects_id?: string | null | undefined;
  position?: number | null | undefined;
};

export const NullableSeverityMatrixImpactEntity$zodSchema: z.ZodType<
  NullableSeverityMatrixImpactEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  affects_id: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  position: z.number().int().nullable().optional(),
  type: z.string().nullable().optional(),
}).describe("SeverityMatrix_ImpactEntity model");
