/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NullableConversationsAPIEntitiesChannel = {
  name?: string | null | undefined;
};

export const NullableConversationsAPIEntitiesChannel$zodSchema: z.ZodType<
  NullableConversationsAPIEntitiesChannel,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().nullable().optional(),
});
