/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NullableIncidentsContextObjectEntity = {
  object_type?: string | null | undefined;
  object_id?: string | null | undefined;
  context_tag?: string | null | undefined;
  context_description?: string | null | undefined;
};

export const NullableIncidentsContextObjectEntity$zodSchema: z.ZodType<
  NullableIncidentsContextObjectEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  context_description: z.string().nullable().optional(),
  context_tag: z.string().nullable().optional(),
  object_id: z.string().nullable().optional(),
  object_type: z.string().nullable().optional(),
});
