/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConversationsAPIEntitiesReference,
  ConversationsAPIEntitiesReference$zodSchema,
} from "./conversationsapientitiesreference.js";
import {
  IncidentsStatusPageEntity,
  IncidentsStatusPageEntity$zodSchema,
} from "./incidentsstatuspageentity.js";

/**
 * Event_NoteEntity model
 */
export type NullableEventNoteEntity = {
  id?: string | null | undefined;
  body?: string | null | undefined;
  created_at?: string | null | undefined;
  status_pages?: Array<IncidentsStatusPageEntity> | null | undefined;
  conversations?: Array<ConversationsAPIEntitiesReference> | null | undefined;
};

export const NullableEventNoteEntity$zodSchema: z.ZodType<
  NullableEventNoteEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: z.string().nullable().optional(),
  conversations: z.array(ConversationsAPIEntitiesReference$zodSchema).nullable()
    .optional(),
  created_at: z.string().datetime({ offset: true }).nullable().optional(),
  id: z.string().nullable().optional(),
  status_pages: z.array(IncidentsStatusPageEntity$zodSchema).nullable()
    .optional(),
}).describe("Event_NoteEntity model");
