/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NullableAuthorEntity,
  NullableAuthorEntity$zodSchema,
} from "./nullableauthorentity.js";

export type NullableTeamEntityLite = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  signals_ical_url?: string | null | undefined;
  created_by?: NullableAuthorEntity | null | undefined;
  in_support_hours?: boolean | null | undefined;
};

export const NullableTeamEntityLite$zodSchema: z.ZodType<
  NullableTeamEntityLite,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).nullable().optional(),
  created_by: NullableAuthorEntity$zodSchema.nullable().optional(),
  description: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  in_support_hours: z.boolean().nullable().optional(),
  name: z.string().nullable().optional(),
  signals_ical_url: z.string().nullable().optional(),
  slug: z.string().nullable().optional(),
  updated_at: z.string().datetime({ offset: true }).nullable().optional(),
});
