/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Attachments_LinkEntity model
 */
export type NullableAttachmentsLinkEntity = {
  id?: string | null | undefined;
  type?: string | null | undefined;
  display_text?: string | null | undefined;
  href_url?: string | null | undefined;
  icon_url?: string | null | undefined;
  editable?: boolean | null | undefined;
  deletable?: boolean | null | undefined;
};

export const NullableAttachmentsLinkEntity$zodSchema: z.ZodType<
  NullableAttachmentsLinkEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  deletable: z.boolean().nullable().optional(),
  display_text: z.string().nullable().optional(),
  editable: z.boolean().nullable().optional(),
  href_url: z.string().nullable().optional(),
  icon_url: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  type: z.string().nullable().optional(),
}).describe("Attachments_LinkEntity model");
