/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * SeverityMatrix_ConditionEntity model
 */
export type NullableSeverityMatrixConditionEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  position?: number | null | undefined;
};

export const NullableSeverityMatrixConditionEntity$zodSchema: z.ZodType<
  NullableSeverityMatrixConditionEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  position: z.number().int().nullable().optional(),
}).describe("SeverityMatrix_ConditionEntity model");
