/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NullableSignalsAPITargetEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  type?: string | null | undefined;
  team_id?: string | null | undefined;
  is_pageable?: boolean | null | undefined;
};

export const NullableSignalsAPITargetEntity$zodSchema: z.ZodType<
  NullableSignalsAPITargetEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().nullable().optional(),
  is_pageable: z.boolean().nullable().optional(),
  name: z.string().nullable().optional(),
  team_id: z.string().nullable().optional(),
  type: z.string().nullable().optional(),
});
