/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NullableIntegrationEntity = {
  id?: string | null | undefined;
  integration_name?: string | null | undefined;
  integration_slug?: string | null | undefined;
  display_name?: string | null | undefined;
  created_at?: string | null | undefined;
};

export const NullableIntegrationEntity$zodSchema: z.ZodType<
  NullableIntegrationEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).nullable().optional(),
  display_name: z.string().nullable().optional(),
  id: z.string().nullable().optional(),
  integration_name: z.string().nullable().optional(),
  integration_slug: z.string().nullable().optional(),
});
