/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PublicApiv1IncidentsSuccinctEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  number?: number | null | undefined;
};

export const PublicApiv1IncidentsSuccinctEntity$zodSchema: z.ZodType<
  PublicApiv1IncidentsSuccinctEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  number: z.number().int().nullable().optional(),
});
