/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = { api_key: string };

export const Security$zodSchema: z.ZodType<Security, z.ZodTypeDef, unknown> = z
  .object({
    api_key: z.string(),
  });
