/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SignalsAPINotificationPolicyItemComplianceEntity = {
  notification_policy_item_id?: string | null | undefined;
  is_compliant?: boolean | null | undefined;
};

export const SignalsAPINotificationPolicyItemComplianceEntity$zodSchema:
  z.ZodType<
    SignalsAPINotificationPolicyItemComplianceEntity,
    z.ZodTypeDef,
    unknown
  > = z.object({
    is_compliant: z.boolean().nullable().optional(),
    notification_policy_item_id: z.string().nullable().optional(),
  });
