/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Update retrospective field value
 */
export type UpdateIncidentRetrospectiveField = {
  dynamic_input_field_id?: string | null | undefined;
  value: string;
};

export const UpdateIncidentRetrospectiveField$zodSchema: z.ZodType<
  UpdateIncidentRetrospectiveField,
  z.ZodTypeDef,
  unknown
> = z.object({
  dynamic_input_field_id: z.string().nullable().optional(),
  value: z.string(),
}).describe("Update retrospective field value");
